var locales = {
  en: {
    message: {
      codeImport: 'Import coding',
      valueSetImport: 'Import Value Set',
      loinc: 'LOINC',
      'icd9-cm': 'ICD9-CM',
      aic: 'AIC',
      atc: 'ATC',
      crossMappingApproval: 'Cross Mapping approval',
      localeCodeImport: 'Mapping Import to Locale Code',
      deleteCodeSystem: 'Delete Code System',
      back: 'Back',
      cancel: 'Cancel',
      save: 'Save',
      version: 'Version',
      aicVersion: 'AIC Version',
      atcVersion: 'ATC Versione',
      fileLoincItalia: 'File LOINC Italia',
      fileLoincInternational: 'File LOINC International',
      fileLoincMapTo: 'File LOINC Map To*',
      releaseDate: 'Release Date',
      releaseDateInfo: 'La data di release è una data importante perchè viene utilizzata dal sistema per stabilire l\'ordine di successione cronologica delle versione',
      oid: 'oid',
      ontologyName: 'Ontology name',
      description: 'Description',
      localCodeSystemName: 'Code system name',
      file: 'File',
      fileFarmaciClasseA: 'File Farmaci Classe A',
      fileFarmaciClasseH: 'File Farmaci Classe H',
      fileFarmaciClasseC: 'File Farmaci Classe C',
      fileFarmaciEquivalenti: 'File Farmaci Equivalenti',
      fileFarmaciAtc: 'Farmaci ATC',
      fileItaIcd9Cm: 'File ICD9-CM italiano',
      fileEnIcd9Cm: 'File ICD9-CM inglese',
      approve: 'Approva',
      reject: 'Rifiuta',
      delete: 'Elimina',
      code: 'Code',
      name: 'Name',
      association: 'Assocation',
      codeSystemName: 'Code System Name',
      type: 'Type',
      operations: 'Operations',
      labelLoading: 'Loading...',
      labelOntological: 'Ontological',
      labelTaxonomic: 'Taxonomic',
      labelCrossMapping: 'Cross Mapping',
      labelLink: 'Link',
      warning: 'Attenzione',
      cantImport: 'An Import is already in progress.',
      noCrossMappings: 'There are not cross Mappings to validate.',
      importInProgress: 'The Import request is in progress. Please check later it has been execution.',
      importError: 'Error during the Import process',
      deleteOk: 'The delete of the code system is ok',
      deleteError: 'Error during the code system deleting',
      close: 'Close',
      mappingImport: 'Mapping Import',
      manageMapping: 'Manege Mapping ',
      import: 'Import',
      versionName: 'Version name',
      selectTheTwoCodeSystemToMap: 'Select the two code system to map',
      localCodeSystemNameAdditionalInfo: 'Indicare il nome nella forma "NomeLaboratorio_Sede_Specialità", es. "ASL 1_Perugia_Chimica".',
      localCodeDelete: 'Delete Mapping to local code',
      mappingDelete: 'Delete Mapping',
      valueSetDelete: 'Delete Value Set',
      deleteLocalCodeSystemOk: 'The delete are completed',
      deleteLocalCodeSystemError: 'Error during deleting',
      mapping: 'Mapping',
      errorDeletingMapping: 'Error during the Mapping deleting',
      successDeletingMapping: 'Successfully Mapping deleting',
      selectMapping: 'Select Mapping',
      codLocale: "Local Codification",
      csvCol: "CSV Column",
      fileLocale: "New file Code System",
      fileItStandardLocal: 'New file Code System ITA',
      fileEnStandardLocal: 'New file Code System ENG',
      upload: "Upload",
      uploadStandardLocalError400: "<br>The file uploaded in :lang language does not have the following required columns:<br> :columns <br>",
      uploadStandardLocalError400_error_invert:"The 2 files have been reversed",
      uploadStandardLocalError400_error_lenght_header:"The 2 files do not have the same number of columns",
      uploadStandardLocalError400_error_headerPrimary_not_present:"The file has no header",
      uploadStandardLocalError400_error_lenght_row:"The 2 files do not have the same number of rows",
      uploadStandardLocalError400_error_lenght_primary_header: "The number of field in the end does not respect the previous version",
	  uploadStandardLocalError422: "Empty file",
	  uploadStandardLocalError: "An error occured while uploading file",
	  localCsvInfo: "CSV properties",
	  columns: "Columns",
	  rows: "Rows",
	  typing: "Data typing",
	  uploadDone: "Upload done.",
	  domain: "Domain",
	  codeSystemType: "Code system type",
	  STANDARD_NATIONAL: "Standard/National",
	  LOCAL: "Local",
	  STANDARD_NATIONAL_STATIC:"",
	  VALUE_SET:"Value Set type",
	  classification: "Classification",
	  nomenclature: "Nomenclature",
	  organization: "Organization",
	  manageCodeSystems: "Manage Code Systems",
	  codeSystem: "Code System",
	  currentVersion: "Last imported version",
	  tipology: "Tipology",
	  actions: "Actions",
	  newCodeSystemLocal: "Import new Code System",
	  newCodeSystemStandard: "Import new Code System Standard/National",
	  chooseVersionDelete: "Choose version to delete",
	  importLocalBadRequest: "Invalid mapping type: missing code or description",
	  importLocalBadRequestCsvField:"Invalid mapping type: missing code or description",
	  importLocalBadRequestFormField:"Invalid form field",
	  mappingInfos: "Fields required: code, description",
	  newValueSet: "Import new ValueSet",
	  valueSet: "ValueSet",
	  manageValueSet: "Manage ValueSet",
	  importValueSet: "Import ValueSet",
	  fileItValueSet: "New file ValueSet ITA",
	  fileEnValueSet: "New file ValueSet ENG",
	  deleteValueSet: "Delete ValueSet",
	  importCodeSystemStandard: "Import new Code System Standard/Nazionale",
	  importCodeSystemLocal: "Import new Code System Local",
	  newMapping: "Import new Mapping",
	  newVersion: "Import new Version",
	  localeCodeManageMapping: 'Manage Mapping LOINC',
	  mappingLocalNotAvaiable: 'Local mapping not available with ',
	  hasOntology: "Has ontology",
	  mandatory:"mandatory",
	  localCatalog:"Cataloghi locali mappati a LOINC",
    },
  },
  it: {
    message: {
      codeImport: 'Import Code System',
      valueSetImport: 'Import Value Set',
      loinc: 'LOINC',
      'icd9-cm': 'ICD9-CM',
      aic: 'AIC',
      atc: 'ATC',
      crossMappingApproval: 'Approvazione Cross Mapping',
      localeCodeImport: 'Import Mapping verso LOINC',
      deleteCodeSystem: 'Cancellazione Code System',
      back: 'Indietro',
      cancel: 'Annulla',
      save: 'Salva',
      version: 'Versione',
      aicVersion: 'Versione AIC',
      atcVersion: 'Versione ATC',
      fileLoincItalia: 'File LOINC Italia',
      fileLoincInternational: 'File LOINC International',
      fileLoincMapTo: 'File LOINC Map To*',
      releaseDate: 'Release Date',
      releaseDateInfo: 'La data di release è una data importante perchè viene utilizzata dal sistema per stabilire l\'ordine di successione cronologica delle versione',
      oid: 'oid',
      ontologyName: 'Nome ontologia',
      description: 'Descrizione',
      localCodeSystemName: 'Nome codifica locale',
      file: 'File',
      fileFarmaciClasseA: 'File Farmaci Classe A',
      fileFarmaciClasseH: 'File Farmaci Classe H',
      fileFarmaciClasseC: 'File Farmaci Classe C',
      fileFarmaciEquivalenti: 'File Farmaci Equivalenti',
      fileFarmaciAtc: 'Farmaci ATC',
      fileItaIcd9Cm: 'File ICD9-CM italiano',
      fileEnIcd9Cm: 'File ICD9-CM inglese',
      approve: 'Approva',
      reject: 'Rifiuta',
      delete: 'Elimina',
      code: 'Codice',
      name: 'Nome',
      association: 'Associazione',
      codeSystemName: 'Sistema di Codifica',
      type: 'Tipo',
      operations: 'Operazioni',
      labelLoading: 'Caricamento...',
      labelOntological: 'Ontologico',
      labelTaxonomic: 'Tassonomico',
      labelCrossMapping: 'Cross Mapping',
      labelLink: 'Link',
      warning: 'Attenzione',
      cantImport: 'Un Import è già in esecuzione.',
      noCrossMappings: 'Non ci sono cross Mapping da validare.',
      importInProgress: 'La richiesta di Import è stata presa in carico. Si prega di controllare più tardi l\'avvenuta esecuzione.',
      importError: 'Errore in fase di Import',
      deleteOk: 'La cancellazione del code system è avvenuta con successo',
      deleteError: 'Errore in fase di cancellazione del code system',
      close: 'Chiudi',
      mappingImport: 'Import Mapping',
      manageMapping: 'Gestione Mapping',
      import: 'Importa',
      versionName: 'Nome versione',
      selectTheTwoCodeSystemToMap: 'Selezionare i sistemi di codifica mappati',
      localCodeSystemNameAdditionalInfo: 'Indicare il nome nella forma "NomeLaboratorio_Sede_Specialità", es. "ASL 1_Perugia_Chimica".',
      localCodeDelete: 'Cancellazione Mapping a codifiche locali',
      mappingDelete: 'Cancellazione Mapping',
      valueSetDelete: 'Cancellazione Value Set',
      deleteLocalCodeSystemOk: 'La cancellazione è avvenuta con successo',
      deleteLocalCodeSystemError: 'Errore in fase di cancellazione',
      mapping: 'Mapping',
      errorDeletingMapping: 'Errore in fase di cancellazione del Mapping',
      successDeletingMapping: 'La cancellazione del Mapping è avvenuta con successo',
      selectMapping: 'Seleziona Mapping',
      codLocale: "Codifica Locale",
      csvCol: "Colonna CSV",
      fileLocale: "File nuovo Code System",
      fileItStandardLocal: 'File nuovo Code System italiano',
      fileEnStandardLocal: 'File nuovo Code System inglese',
      upload: "Carica",
      uploadStandardLocalError400: "<br>Il file caricato in lingua :lang, non presenta le seguenti colonne richieste:<br> :columns <br>",
      uploadStandardLocalError400_error_invert:"I 2 file sono stati invertiti",
      uploadStandardLocalError400_error_lenght_header:"I 2 file non hanno lo stesso numero di colonne",
      uploadStandardLocalError400_error_headerPrimary_not_present:"Il file non ha nessuna intestazione",
      uploadStandardLocalError400_error_lenght_row:"I 2 file non hanno lo stesso numero di righe",
      uploadStandardLocalError400_error_lenght_primary_header:"Il numero di campi presenti nel fine non rispetta la precedene versione",
	  uploadStandardLocalError422: "Il file caricato è vuoto",
	  uploadStandardLocalError: "Si è verificato un errore durante l'importazione del file",
	  localCsvInfo: "Informazioni csv",
	  columns: "Colonne",
	  rows: "Righe",
	  typing: "Tipizzazione dati",
	  uploadDone: "Il file è stato caricato con successo.",
	  domain: "Dominio",
	  codeSystemType: "Tipo di code system",
	  STANDARD_NATIONAL: "Standard/Nazionale",
	  LOCAL: "Locale",
	  STANDARD_NATIONAL_STATIC:"",
	  VALUE_SET:"Value Set",
	  classification: "Classificazione",
	  nomenclature: "Nomenclatura",
	  organization: "Organizzazione",
	  manageCodeSystems: "Gestione Code Systems",
	  codeSystem: "Code System",
	  currentVersion: "Ultima versione importata",
	  tipology: "Tipologia",
	  actions: "Azioni",
	  newCodeSystemLocal: "Import nuovo Code System Locale",
	  newCodeSystemStandard: "Import nuovo Code System Standard/Nazionale",
	  chooseVersionDelete: "Seleziona versione da eliminare",
	  importLocalBadRequest: "Mapping colonne non valido: codice o descrizione non definiti",
	  importLocalBadRequestCsvField:"Mapping colonne non valido: codice o descrizione non definiti",
	  importLocalBadRequestFormField:"I dati inseriti non sono validi",
	  mappingInfos: "Campi richiesti: codice, descrizione",
	  newValueSet: "Import nuovo ValueSet",
	  valueSet: "ValueSet",
	  manageValueSet: "Gestione ValueSet",
	  importValueSet: "Import ValueSet",
	  fileItValueSet: "File nuovo ValueSet italiano",
	  fileEnValueSet: "File nuovo ValueSet inglese",
	  deleteValueSet: "Cancellazione ValueSet",
	  importCodeSystemStandard: "Import nuovo Code System Standard/Nazionale",
	  importCodeSystemLocal: "Import nuovo Code System Locale",
	  newMapping: "Import nuovo Mapping",
	  newVersion: "Import nuova Versione",
	  localeCodeManageMapping: 'Gestione Mapping LOINC',
	  mappingLocalNotAvaiable: 'Mapping Locale non disponibile con ',
	  hasOntology: "Ontologia presente",
	  mandatory:"oblbigatorio",
	  localCatalog: "Cataloghi locali mappati a LOINC",
    },
  }
};


Vue.use(VueI18n);
Vue.config.lang = 'it';
Vue.config.fallbackLang = 'it'

Object.keys(locales).forEach(function (lang) {
  Vue.locale(lang, locales[lang])
});
